# Specify a non-default branch for dependabot

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
    target-branch: dev
    versioning-strategy: increase-if-necessary
    allow:
      - dependency-type: "direct"
    labels:
      - "dependencies"
